package com.pojo;

// Generated Mar 20, 2019 3:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * Register generated by hbm2java
 */
public class Register implements java.io.Serializable {

	private Integer rid;
	private Role role;
	private String name;
	private String email;
	private String password;

	public Register() {
	}

	public Register(Role role, String name, String email, String password) {
		this.role = role;
		this.name = name;
		this.email = email;
		this.password = password;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
