package com.pojo;

// Generated Mar 20, 2019 3:15:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * Salary generated by hbm2java
 */
public class Salary implements java.io.Serializable {

	private Integer sid;
	private Employee employee;
	private Double salary;
	private Double bonus;
	private Double total;
	private String month;

	public Salary() {
	}

	public Salary(Employee employee, Double salary, Double bonus, Double total, String month) {
		this.employee = employee;
		this.salary = salary;
		this.bonus = bonus;
		this.total = total;
		this.month = month;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	public Double getBonus() {
		return this.bonus;
	}

	public void setBonus(Double bonus) {
		this.bonus = bonus;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

}
